---

- name: NM_CONTROLLED=no
  lineinfile: >-
    dest="/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
    state=present
    regexp="NM_CONTROLLED=.*"
    line="NM_CONTROLLED=no"
  when: item != "lo"
  with_items: "{{ ansible_interfaces }}"

