---

#- name: RDO repo
#  yum: name=https://rdoproject.org/repos/rdo-release.rpm state=installed
#
#- name: check if RDO Manager repo file exists
#  shell: grep baseurl /etc/yum.repos.d/rdo-management-trunk.repo
#  ignore_errors: true
#  always_run: yes
#  changed_when: false
#  register: result
#
#- name: RDO Manager repo
#  shell: curl -o /etc/yum.repos.d/rdo-management-trunk.repo http://trunk-mgt.rdoproject.org/centos-kilo/current-passed-ci/delorean-rdo-management.repo
#  when: result.rc != 0
#
##- name: packstack
##  yum: name=openstack-packstack state=installed

- name: RDO Mitaka Delorean for core openstack
  get_url: url=https://trunk.rdoproject.org/centos7-mitaka/current-passed-ci/delorean.repo dest=/etc/yum.repos.d/delorean-mitaka.repo

- name: RDO Mitaka Deps
  get_url: url=http://trunk.rdoproject.org/centos7-mitaka/delorean-deps.repo dest=/etc/yum.repos.d/delorean-deps-mitaka.repo

#- name: RDO Trunk Delorean for core openstack
#  get_url: url=http://trunk.rdoproject.org/centos7/current-tripleo/delorean.repo dest=/etc/yum.repos.d/delorean.repo
#
#- name: RDO Trunk Delorean for TripleO
#  get_url: url=http://trunk.rdoproject.org/centos7/current/delorean.repo dest=/etc/yum.repos.d/delorean-current.repo
#
#- name: RDO Trunk Deps
#  get_url: url=http://trunk.rdoproject.org/centos7/delorean-deps.repo dest=/etc/yum.repos.d/delorean-deps.repo

#- name: update
#  lineinfile: >-
#    dest=/etc/yum.repos.d/delorean-current.repo
#    state=present
#    regexp="\[delorean\]"
#    line="[delorean-current]"
#
#- name: update 2
#  lineinfile: >-
#    dest=/etc/yum.repos.d/delorean-current.repo
#    state=present
#    line="includepkgs=diskimage-builder,instack,instack-undercloud,os-apply-config,os-cloud-config,os-collect-config,os-net-config,os-refresh-config,python-tripleoclient,tripleo-common,openstack-tripleo-heat-templates,openstack-tripleo-image-elements,openstack-tripleo,openstack-tripleo-puppet-elements,openstack-puppet-modules"
#    regexp="includepkgs=.*"
