---

- hosts: test-mgmt
  vars_files:
    - "env_vars/{{ env_name }}.yml"
  roles:
    - repository
    - packages
    - user
    - no_firewalld
    - nic_ifcfg
    - nic_ifcfg_manual
    - nic_noNM
    - hostname
    - disable_NetworkManager
    - ntp

    - grub_console
    - git_clone
#    - rdo
#    - devstack
