---

#- hosts: osp
- hosts: deployed_hosts
  vars_files:
#    - "env_vars/{{ env_name }}.yml"
    - "env_vars/osp7.yml"
  roles:
#    - ntp
    - timezone
    - repository
#    - packages
    - user
    - grub_console
#    - git_clone
    - osp-d_tools_for_deployed_nodes
