---

- hosts: fedora-br0
  vars_files:
    - "env_vars/{{ env_name }}.yml"
  roles:
    - no_firewalld
    - nic_ifcfg
    - nic_ifcfg_manual
    - nic_noNM
    - hostname
    - disable_NetworkManager

- hosts: fedora-mgmt
  roles:
#    - packages
#    - user
#    - ntp
#    - grub_console
#    - git_clone
##    - rdo
    - devstack
