---

- name: yum local repository for RHEL
  template: src=localrepo-rhel7.repo.j2 dest=/etc/yum.repos.d/localrepo-rhel7.repo
  when: ansible_os_family == "RedHat" and ansible_distribution == "RedHat"

- name: EPEL repo for CentOS
  yum: name=http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=installed
  when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS"

- name: update packages
  yum: name=* state=latest

- name: install basic packages
  yum: name={{ item }} state=installed
  with_items: "{{system_packages}}"
