---

- name: update packages - yum
  yum: name=* state=latest
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

- name: update packages - dnf
  dnf: name=* state=latest
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- name: install basic packages - yum
  yum: name={{ item }} state=installed
  with_items: "{{system_packages}}"
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

- name: install basic packages - dnf
  dnf: name={{ item }} state=installed
  with_items: "{{system_packages}}"
  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"
