---

- name: ntp.conf 1
  lineinfile: >-
    dest=/etc/ntp.conf
    state=absent
    regexp="^server [0-9]\.{fedora,centos,rhel}\.pool\.ntp\.org iburst"

- name: ntp.conf 2
  lineinfile: >-
    dest=/etc/ntp.conf
    state=present
    line="server {{ ntp_server1 }} iburst"

- name: ntp.conf 3
  lineinfile: >-
    dest=/etc/ntp.conf
    state=present
    line="server {{ ntp_server2 }} iburst"

- name: restart ntp
  service: name=ntpd enabled=yes state=restarted
