---

- name: mon_initial
  shell: ceph-deploy new {{ mon_nodes[0].name }} chdir=~ori/ceph-config creates=~ori/ceph-config/ceph.conf
  when: inventory_hostname == "{{ admin_node.addr }}"

- name: check ceph.conf
  shell: grep public_network ~ori/ceph-config/ceph.conf
  always_run: true
  changed_when: false
  register: result
  failed_when: result.rc not in [0, 1]
  when: inventory_hostname == "{{ admin_node.addr }}"
#- debug: var=result

- name: create ceph.conf.append
  template: src=ceph.conf.j2 dest=/tmp/ceph.conf.append
  when: inventory_hostname == "{{ admin_node.addr }}" and result.rc != 0
  
- name: create ceph.conf
  shell: cat /tmp/ceph.conf.append >> ~ori/ceph-config/ceph.conf
  when: inventory_hostname == "{{ admin_node.addr }}" and result.rc != 0
  
- name: check /etc/ceph on admin node
  shell: ls /etc/ceph
  always_run: true
  changed_when: false
  register: result
  ignore_errors: yes
  when: inventory_hostname == "{{ admin_node.addr }}"

- name: install ceph on admin node
  shell: ceph-deploy install {{ admin_node.name }} chdir=~ori/ceph-config
  when: inventory_hostname == "{{ admin_node.addr }}" and result.rc != 0
  
#- name: check /etc/ceph on mon nodes
#  shell: ls /etc/ceph
#  always_run: true
#  changed_when: false
#  register: result
#  ignore_errors: yes
#  when: inventory_hostname == "{{ item.addr }}"
#  with_items: "{{ mon_nodes }}"
#- debug: var=result
#
#- debug: var=hostvars

- name: make args for nodes
  set_fact:
    opt_str: '{{ item.name }}'
  register: opts
  when: inventory_hostname == "{{ admin_node.addr }}"
  with_items:
    - "{{ mon_nodes }}"
    - "{{ osd_nodes }}"
#- debug: var=opts

#- name: check /etc/apt/sources.list.d/ceph.list on mon node
#  shell: ls /etc/apt/sources.list.d/ceph.list
#  always_run: true
#  changed_when: false
#  register: cephlist
#  ignore_errors: yes
#  when: inventory_hostname == "{{ admin_node.addr }}"

- name: install repo file on nodes
  shell: ceph-deploy install --repo {{ opts.results | join(' ', attribute='ansible_facts.opt_str') }} chdir=~ori/ceph-config
  when: inventory_hostname == "{{ admin_node.addr }}"

- name: install ceph on nodes
  shell: ceph-deploy install {{ opts.results | join(' ', attribute='ansible_facts.opt_str') }} chdir=~ori/ceph-config
  when: inventory_hostname == "{{ admin_node.addr }}"

