---

- name: copy files
  sudo: yes
  sudo_user: stack
  shell: cp -rf /usr/share/openstack-tripleo-heat-templates ~/my_templates

- name: custom yaml
  sudo: yes
  sudo_user: stack
  copy: src={{ item }} dest=~/
  with_items:
    - network-environment.yaml
    - swap_on.yaml

- name: firstboot directory
  sudo: yes
  sudo_user: stack
  file: path=~/firstboot state=directory

- name: firstboot files
  sudo: yes
  sudo_user: stack
  copy: src={{ item }} dest=~/firstboot/
  with_items:
    - enable_swap.yaml

- name: nic-configs directory
  sudo: yes
  sudo_user: stack
  file: path=~/nic-configs state=directory

- name: nic-configs files
  sudo: yes
  sudo_user: stack
  copy: src={{ item }} dest=~/nic-configs
  with_items:
    - controller.yaml
    - compute.yaml
    - cinder-storage.yaml

- name: setup_openstack
  sudo: yes
  sudo_user: stack
  git: repo=git@github.com:orimanabu/setup_openstack.git dest=setup_openstack accept_hostkey=yes
